version: '3.1'

services:

  db:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword  # Replace with a secure password
      MARIADB_DATABASE: mydatabase         # Database name
      MARIADB_USER: myuser                 # Database user
      MARIADB_PASSWORD: mypassword         # Replace with a secure password
    ports:
      - 3306:3306                          # Expose MariaDB on port 3306
    volumes:
      - mariadb_data:/var/lib/mysql        # Persist database data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer-container
    restart: always
    ports:
      - 8080:8080                          # Expose Adminer on port 8080
    depends_on:
      - db                                 # Ensure Adminer starts after the database
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - 6379:6379                          # Expose Redis on port 6379
    volumes:
      - redis_data:/data                   # Persist Redis data
    networks:
      - app-network

volumes:
  mariadb_data:                            # Define a volume for database persistence
  redis_data:                              # Define a volume for Redis persistence

networks:
  app-network:                             # Define a custom network