"""Add column incorrect_count Initial migration

Revision ID: e432a856cb40
Revises: 
Create Date: 2024-11-17 17:52:07.593704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e432a856cb40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_counts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incorrect_count', sa.Integer(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_counts', schema=None) as batch_op:
        batch_op.drop_column('incorrect_count')

    # ### end Alembic commands ###
